name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      # uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        INPUT_HOST: ${{ secrets.SERVER_IP }}
        INPUT_USERNAME: ${{ secrets.SERVER_USERNAME }}
        INPUT_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        INPUT_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        INPUT_SOURCE: "/*"
        INPUT_TARGET: "/path/to/remote/directory/"
        INPUT_PORT: "8080:80"
        

    - name: Reload Nginx
      run: ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} 'sudo nginx -s reload'
