name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "quiz-app/*"
        target: "/path/to/remote/directory/"

    - name: Reload Nginx
      run: ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} 'sudo nginx -s reload'
